# Site settings
title: Joshua Hatzenbuehler
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joshua Hatzenbuehler
user_description: I'm a semi-nomad Engineering Manager, always searching for the next challenge. Lately, I've been working at Plus One Robotics to create scalable solutions for computer vision in logisitics.
user_title: Engineering Manager
email: joshuahatz@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
